#!/bin/sh

# Show Hidden Files in OSX
echo  "Showing Hidden Files in OSX..."
  defaults write com.apple.finder AppleShowAllFiles TRUE
  killall Finder

# Install Homebrew
echo  "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  brew doctor

# Create SSH Keys nd prompt user to add them to Github
echo  "Checking for SSH key in ~/.ssh/id_rsa.pub, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo  "Copying public key to clipboard."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy

echo  "Open https://github.com/account/ssh to add your key [Enter]: "
  read key
  echo "\n Testing Github Authentication via ssh"
  ssh -T git@github.com

# Install Git
echo  "Installing Git..."
  brew install git

# Before we do any config install our dotfiles
echo  "Installing Newism dot files..."
  git clone git://github.com/newism/dotfiles.git ~/.dotfiles
  bash ~/.dotfiles/bootstrap.sh
  bash ~/.dotfiles/osx
  source ~/.bash_profile

echo  "Creating ~/.bash_profile.local to store local bash config..."
  echo 'export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"' >> ~/.bash_profile.local
  echo 'export PATH="$(brew --prefix)/bin:$PATH"' >> .bash_profile.local

echo  "Adding Key Chain helper for Git to ~/.bash_profile.local..."
  echo "git config --global credential.helper osxkeychain" >> .bash_profile.local

echo "Adding Global Git Config..."
  echo  "Whats your name? [Enter]: "
  read name
  echo "What's your email? [Enter]: "
  read email
  echo "git config --global user.name \"$name\"" >> .bash_profile.local
  echo "git config --global user.email \"$email\"" >> .bash_profile.local

echo "Installing Phantom JS for Javascript testing..."
  brew install phantomjs

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing optipng, a PNG optimizer that recompresses the image files to a smaller size, without losing any information. ..."
  brew install optipng

source ~/.bash_profile

curl -s https://raw.github.com/newism/laptop/master/git | sh
curl -s https://raw.github.com/newism/laptop/master/ruby | sh
curl -s https://raw.github.com/newism/laptop/master/node | sh
curl -s https://raw.github.com/newism/laptop/master/php | sh
