#!/bin/sh

echo -e "\nInstalling Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo 'export PATH="$(brew --prefix)/bin:$PATH"' >> .bash_profile.local
  source ~/.bash_profile.local

echo -e "\nInstalling Git..."
  brew install git

echo -e "\nChecking for SSH key in ~/.ssh/id_rsa.pub, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo -e "\nInstalling Newism dot files..."
  git clone git://github.com/newism/dotfiles.git ~/.dotfiles
  bash ~/.dotfiles/bootstrap.sh
  bash ~/.dotfiles/.osx

echo -e "\nCreating ~/.bash_profile.local to store local bash config..."
  touch ~/.bash_profile.local
  echo 'export PATH=/usr/local/bin:$PATH' >> .bash_profile.local
  source ~/.bash_profile.local
  source ~/.bash_profile

echo -e "\nCopying public key to clipboard."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy

echo -e "\nOpen https://github.com/account/ssh to add your key"
  read -s -n1 -p "Have you added your key to Github? [Y/n] " key
  echo "\n Testing Github Authentication via ssh"
  ssh -T git@github.com

echo -e "\nAdding Key Chain helper for Git"
  curl -s -O http://github-media-downloads.s3.amazonaws.com/osx/git-credential-osxkeychain
  chmod u+x git-credential-osxkeychain
  sudo mv git-credential-osxkeychain `dirname \`which git\``
  git config --global credential.helper osxkeychain


echo "Installing Phantom JS for Javascript testing..."
  brew install phantomjs

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing optipng, a PNG optimizer that recompresses the image files to a smaller size, without losing any information. ..."
  brew install optipng

source ~/.bash_profile

curl -s https://raw.github.com/newism/laptop/master/git | sh
curl -s https://raw.github.com/newism/laptop/master/ruby | sh
curl -s https://raw.github.com/newism/laptop/master/node | sh
curl -s https://raw.github.com/newism/laptop/master/php | sh
